//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/3rdPersonCamera/Settings/Input/TPC_Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ThirdPersonCamera
{
    public partial class @TPC_Input: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @TPC_Input()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""TPC_Input"",
    ""maps"": [
        {
            ""name"": ""CameraMovement"",
            ""id"": ""a2336856-9459-4861-8cce-8a39b61fe236"",
            ""actions"": [
                {
                    ""name"": ""CameraAxis"",
                    ""type"": ""Value"",
                    ""id"": ""d98e3ae0-717e-4df9-b939-2a169cc5f5c9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ControllerCameraAxis"",
                    ""type"": ""Value"",
                    ""id"": ""6a32abec-8a04-436e-b60a-42a1985bce96"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EnableFreeLook"",
                    ""type"": ""Button"",
                    ""id"": ""eaa64a73-5c9f-49c9-bcd4-6bc53e155e9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ForceTargetDirection"",
                    ""type"": ""Button"",
                    ""id"": ""d9b50249-3096-4d01-be69-3ce0884b3e0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""b5c95f89-ee87-4316-953a-b6c6a3b18411"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseVisibilityToggle"",
                    ""type"": ""Button"",
                    ""id"": ""682d8642-ea6e-4c05-9d94-9bd2fe5fa8fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseVisibilityCancel"",
                    ""type"": ""Button"",
                    ""id"": ""da665416-69dc-4463-9841-f7f3c4bd9604"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""e59e6139-1f4f-4f20-a5f3-8c625ca10a16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAimSide"",
                    ""type"": ""Button"",
                    ""id"": ""610698df-a2b0-4bad-aa3c-7860e9020ff3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOn"",
                    ""type"": ""Button"",
                    ""id"": ""b5556520-dabc-4134-bc2e-115544fdabe5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextLockOnTarget"",
                    ""type"": ""Button"",
                    ""id"": ""4dc20924-9792-4c62-8162-d7a8217e9b02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousLockOnTarget"",
                    ""type"": ""Button"",
                    ""id"": ""ef3c4ec3-edb7-4b78-ab11-12bb42d8295c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b66a70d9-e86a-46af-b3fb-b8965d9df31d"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.05,y=0.05)"",
                    ""groups"": """",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c1716154-9c5a-4bbd-9ae6-64c95894c933"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d2b0f6e2-64d5-4213-bbc7-846623822e70"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6053ae30-95a6-4d04-b6ad-e93b88947363"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ec84dd19-a211-4991-8605-77dfdc3977f3"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""CameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ea5be118-2b8d-4e82-a328-0d364b5a9ace"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""EnableFreeLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1b5828c-109e-4905-945e-9ef84422ce41"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""EnableFreeLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae21c697-d971-46be-8362-6a2c0c6d7012"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2b9f935c-8b2c-41f0-ac34-a4f35bcd3891"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2de0872f-a270-4298-96e1-85e88c1cbb19"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2425ed8e-c26b-4640-b898-ec13b6ae91b8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f3e0311c-8620-45a2-9c1c-26de3f466085"",
                    ""path"": ""<Keyboard>/f7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseVisibilityToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""072d452a-ad29-44b9-be3d-b259ac5c434a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse;Gamepad"",
                    ""action"": ""MouseVisibilityCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f86a52f-0810-46c0-9c90-94ef2e242ea5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ForceTargetDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""175f10fc-3b4a-423a-830d-51065ddd5080"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d1d89ee-7a00-4697-991a-7902440f012e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""660a57b4-0b9c-448c-babf-73de3de9ee40"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAimSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a626f7c9-85b2-4cd8-9280-939e17b58dcb"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SwitchAimSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""53f25a8c-9014-41e1-ab23-d69ba4c32a26"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.4,y=0.4)"",
                    ""groups"": """",
                    ""action"": ""ControllerCameraAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6ed9f565-2bef-4180-b43e-cb22cb07e9de"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ControllerCameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3c224985-dee2-43f5-880f-b55779286c78"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ControllerCameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0cb140b2-e445-4886-ba61-80186a410c8b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ControllerCameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""37c0afc1-8644-4794-91ae-5677ea57b6fb"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ControllerCameraAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1f1f7a62-3c7a-4dfa-84fc-6f227294941a"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c09bcb4c-8e0a-465d-9c1c-5b446ccfd054"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51d62bba-1704-4e54-a219-a98dd861f030"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""NextLockOnTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a1d895a-0867-42ce-bc3d-d8f1bde46ee5"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NextLockOnTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff08d481-a038-47d5-abb2-6d456a0ce4b9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""PreviousLockOnTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03727a0d-0fe1-4407-9b9b-d54bd53508b4"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PreviousLockOnTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // CameraMovement
            m_CameraMovement = asset.FindActionMap("CameraMovement", throwIfNotFound: true);
            m_CameraMovement_CameraAxis = m_CameraMovement.FindAction("CameraAxis", throwIfNotFound: true);
            m_CameraMovement_ControllerCameraAxis = m_CameraMovement.FindAction("ControllerCameraAxis", throwIfNotFound: true);
            m_CameraMovement_EnableFreeLook = m_CameraMovement.FindAction("EnableFreeLook", throwIfNotFound: true);
            m_CameraMovement_ForceTargetDirection = m_CameraMovement.FindAction("ForceTargetDirection", throwIfNotFound: true);
            m_CameraMovement_Zoom = m_CameraMovement.FindAction("Zoom", throwIfNotFound: true);
            m_CameraMovement_MouseVisibilityToggle = m_CameraMovement.FindAction("MouseVisibilityToggle", throwIfNotFound: true);
            m_CameraMovement_MouseVisibilityCancel = m_CameraMovement.FindAction("MouseVisibilityCancel", throwIfNotFound: true);
            m_CameraMovement_Aim = m_CameraMovement.FindAction("Aim", throwIfNotFound: true);
            m_CameraMovement_SwitchAimSide = m_CameraMovement.FindAction("SwitchAimSide", throwIfNotFound: true);
            m_CameraMovement_LockOn = m_CameraMovement.FindAction("LockOn", throwIfNotFound: true);
            m_CameraMovement_NextLockOnTarget = m_CameraMovement.FindAction("NextLockOnTarget", throwIfNotFound: true);
            m_CameraMovement_PreviousLockOnTarget = m_CameraMovement.FindAction("PreviousLockOnTarget", throwIfNotFound: true);
        }

        ~@TPC_Input()
        {
            UnityEngine.Debug.Assert(!m_CameraMovement.enabled, "This will cause a leak and performance issues, TPC_Input.CameraMovement.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // CameraMovement
        private readonly InputActionMap m_CameraMovement;
        private List<ICameraMovementActions> m_CameraMovementActionsCallbackInterfaces = new List<ICameraMovementActions>();
        private readonly InputAction m_CameraMovement_CameraAxis;
        private readonly InputAction m_CameraMovement_ControllerCameraAxis;
        private readonly InputAction m_CameraMovement_EnableFreeLook;
        private readonly InputAction m_CameraMovement_ForceTargetDirection;
        private readonly InputAction m_CameraMovement_Zoom;
        private readonly InputAction m_CameraMovement_MouseVisibilityToggle;
        private readonly InputAction m_CameraMovement_MouseVisibilityCancel;
        private readonly InputAction m_CameraMovement_Aim;
        private readonly InputAction m_CameraMovement_SwitchAimSide;
        private readonly InputAction m_CameraMovement_LockOn;
        private readonly InputAction m_CameraMovement_NextLockOnTarget;
        private readonly InputAction m_CameraMovement_PreviousLockOnTarget;
        public struct CameraMovementActions
        {
            private @TPC_Input m_Wrapper;
            public CameraMovementActions(@TPC_Input wrapper) { m_Wrapper = wrapper; }
            public InputAction @CameraAxis => m_Wrapper.m_CameraMovement_CameraAxis;
            public InputAction @ControllerCameraAxis => m_Wrapper.m_CameraMovement_ControllerCameraAxis;
            public InputAction @EnableFreeLook => m_Wrapper.m_CameraMovement_EnableFreeLook;
            public InputAction @ForceTargetDirection => m_Wrapper.m_CameraMovement_ForceTargetDirection;
            public InputAction @Zoom => m_Wrapper.m_CameraMovement_Zoom;
            public InputAction @MouseVisibilityToggle => m_Wrapper.m_CameraMovement_MouseVisibilityToggle;
            public InputAction @MouseVisibilityCancel => m_Wrapper.m_CameraMovement_MouseVisibilityCancel;
            public InputAction @Aim => m_Wrapper.m_CameraMovement_Aim;
            public InputAction @SwitchAimSide => m_Wrapper.m_CameraMovement_SwitchAimSide;
            public InputAction @LockOn => m_Wrapper.m_CameraMovement_LockOn;
            public InputAction @NextLockOnTarget => m_Wrapper.m_CameraMovement_NextLockOnTarget;
            public InputAction @PreviousLockOnTarget => m_Wrapper.m_CameraMovement_PreviousLockOnTarget;
            public InputActionMap Get() { return m_Wrapper.m_CameraMovement; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraMovementActions set) { return set.Get(); }
            public void AddCallbacks(ICameraMovementActions instance)
            {
                if (instance == null || m_Wrapper.m_CameraMovementActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CameraMovementActionsCallbackInterfaces.Add(instance);
                @CameraAxis.started += instance.OnCameraAxis;
                @CameraAxis.performed += instance.OnCameraAxis;
                @CameraAxis.canceled += instance.OnCameraAxis;
                @ControllerCameraAxis.started += instance.OnControllerCameraAxis;
                @ControllerCameraAxis.performed += instance.OnControllerCameraAxis;
                @ControllerCameraAxis.canceled += instance.OnControllerCameraAxis;
                @EnableFreeLook.started += instance.OnEnableFreeLook;
                @EnableFreeLook.performed += instance.OnEnableFreeLook;
                @EnableFreeLook.canceled += instance.OnEnableFreeLook;
                @ForceTargetDirection.started += instance.OnForceTargetDirection;
                @ForceTargetDirection.performed += instance.OnForceTargetDirection;
                @ForceTargetDirection.canceled += instance.OnForceTargetDirection;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @MouseVisibilityToggle.started += instance.OnMouseVisibilityToggle;
                @MouseVisibilityToggle.performed += instance.OnMouseVisibilityToggle;
                @MouseVisibilityToggle.canceled += instance.OnMouseVisibilityToggle;
                @MouseVisibilityCancel.started += instance.OnMouseVisibilityCancel;
                @MouseVisibilityCancel.performed += instance.OnMouseVisibilityCancel;
                @MouseVisibilityCancel.canceled += instance.OnMouseVisibilityCancel;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @SwitchAimSide.started += instance.OnSwitchAimSide;
                @SwitchAimSide.performed += instance.OnSwitchAimSide;
                @SwitchAimSide.canceled += instance.OnSwitchAimSide;
                @LockOn.started += instance.OnLockOn;
                @LockOn.performed += instance.OnLockOn;
                @LockOn.canceled += instance.OnLockOn;
                @NextLockOnTarget.started += instance.OnNextLockOnTarget;
                @NextLockOnTarget.performed += instance.OnNextLockOnTarget;
                @NextLockOnTarget.canceled += instance.OnNextLockOnTarget;
                @PreviousLockOnTarget.started += instance.OnPreviousLockOnTarget;
                @PreviousLockOnTarget.performed += instance.OnPreviousLockOnTarget;
                @PreviousLockOnTarget.canceled += instance.OnPreviousLockOnTarget;
            }

            private void UnregisterCallbacks(ICameraMovementActions instance)
            {
                @CameraAxis.started -= instance.OnCameraAxis;
                @CameraAxis.performed -= instance.OnCameraAxis;
                @CameraAxis.canceled -= instance.OnCameraAxis;
                @ControllerCameraAxis.started -= instance.OnControllerCameraAxis;
                @ControllerCameraAxis.performed -= instance.OnControllerCameraAxis;
                @ControllerCameraAxis.canceled -= instance.OnControllerCameraAxis;
                @EnableFreeLook.started -= instance.OnEnableFreeLook;
                @EnableFreeLook.performed -= instance.OnEnableFreeLook;
                @EnableFreeLook.canceled -= instance.OnEnableFreeLook;
                @ForceTargetDirection.started -= instance.OnForceTargetDirection;
                @ForceTargetDirection.performed -= instance.OnForceTargetDirection;
                @ForceTargetDirection.canceled -= instance.OnForceTargetDirection;
                @Zoom.started -= instance.OnZoom;
                @Zoom.performed -= instance.OnZoom;
                @Zoom.canceled -= instance.OnZoom;
                @MouseVisibilityToggle.started -= instance.OnMouseVisibilityToggle;
                @MouseVisibilityToggle.performed -= instance.OnMouseVisibilityToggle;
                @MouseVisibilityToggle.canceled -= instance.OnMouseVisibilityToggle;
                @MouseVisibilityCancel.started -= instance.OnMouseVisibilityCancel;
                @MouseVisibilityCancel.performed -= instance.OnMouseVisibilityCancel;
                @MouseVisibilityCancel.canceled -= instance.OnMouseVisibilityCancel;
                @Aim.started -= instance.OnAim;
                @Aim.performed -= instance.OnAim;
                @Aim.canceled -= instance.OnAim;
                @SwitchAimSide.started -= instance.OnSwitchAimSide;
                @SwitchAimSide.performed -= instance.OnSwitchAimSide;
                @SwitchAimSide.canceled -= instance.OnSwitchAimSide;
                @LockOn.started -= instance.OnLockOn;
                @LockOn.performed -= instance.OnLockOn;
                @LockOn.canceled -= instance.OnLockOn;
                @NextLockOnTarget.started -= instance.OnNextLockOnTarget;
                @NextLockOnTarget.performed -= instance.OnNextLockOnTarget;
                @NextLockOnTarget.canceled -= instance.OnNextLockOnTarget;
                @PreviousLockOnTarget.started -= instance.OnPreviousLockOnTarget;
                @PreviousLockOnTarget.performed -= instance.OnPreviousLockOnTarget;
                @PreviousLockOnTarget.canceled -= instance.OnPreviousLockOnTarget;
            }

            public void RemoveCallbacks(ICameraMovementActions instance)
            {
                if (m_Wrapper.m_CameraMovementActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICameraMovementActions instance)
            {
                foreach (var item in m_Wrapper.m_CameraMovementActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CameraMovementActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CameraMovementActions @CameraMovement => new CameraMovementActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface ICameraMovementActions
        {
            void OnCameraAxis(InputAction.CallbackContext context);
            void OnControllerCameraAxis(InputAction.CallbackContext context);
            void OnEnableFreeLook(InputAction.CallbackContext context);
            void OnForceTargetDirection(InputAction.CallbackContext context);
            void OnZoom(InputAction.CallbackContext context);
            void OnMouseVisibilityToggle(InputAction.CallbackContext context);
            void OnMouseVisibilityCancel(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnSwitchAimSide(InputAction.CallbackContext context);
            void OnLockOn(InputAction.CallbackContext context);
            void OnNextLockOnTarget(InputAction.CallbackContext context);
            void OnPreviousLockOnTarget(InputAction.CallbackContext context);
        }
    }
}
